### ISSUE TITLE
can the half life of the bounce be quicker?

### ISSUE THREAD

**Issue by russellsamora** [the-pudding/hs-hype#8]

**Comment by ProQuestionAsker** [comment]
Maybe. So I found a way to change the bounce animation (it's actually in the `flow.js` file in a function called `bounce()`) based on [this](https://bl.ocks.org/mbostock/5743979). It worked fine until I tied everything to the timer. the `bounce()` function as I have it written doesn't work inside this line:
```let time = d3.easeBounceOut(timeScale(t - d.trans.delay))```
